using System.Collections.Generic;

namespace PersianLinkBoard
{
    internal static class HtmlSeedData
    {
        public const string DatasetVersion = "kafenet-184-v1";
        public static List<LinkItem> Create()
        {
            return new List<LinkItem>
            {
new LinkItem("سامانه حسام","https://my.cbi.ir/login?","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بوستان دانشجویان ملی مهارت","https://bustan.tvu.ac.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("وام سربازی (سماسو)","https://reg.samasoo.ir/users","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("سجام","https://www.sejam.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("احراز هویت سجام","https://www.sejam.ir/fa/ElectronicAuthentication","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("مای تکس (مالیات)","https://my.tax.gov.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک رسالت","https://qhamian.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("اعتبارسنجی مرات","https://imerat.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("صیادی بانک ملی","https://sayad.bmi.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("قسط کارت اعتباری ملی","https://bmicc.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("اعتبارسنجی بانکی","https://etebaritoapp.ics24.ir/login","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک ملی (بام)","https://baambank.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("فرابانک ملت","https://www.bankmellat.ir/farabank_accommodations.aspx","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک صادرات","https://www.bsi.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک تجارت","https://www.tejaratbank.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک پاسارگاد","https://vbank.bpi.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک سامان","https://www.sb24.ir/home/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک کشاورزی","https://www.bki.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک سپه","https://banksepah.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک مسکن","https://www.bank-maskan.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک شهر","https://www.shahr-bank.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بانک توسعه صادرات","https://bpi.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("سامانه راهبردی مالیات","https://tax.gov.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("صندوق بازنشستگی کشوری","https://www.cspf.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("سامانه چکاوک (استعلام چک)","https://chekavak.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("سامانه صیاد","https://www.cbi.ir","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("قبضینو","https://ghabzino.com/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("قسط بانک ملی (کارت اعتباری)","https://bmicc.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("وام ازدواج","https://ve.cbi.ir/Default.aspx","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بیمه ما","https://myclm.bimehma.com/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بیمه ایران","https://my.iraninsurance.ir/","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("ذینفعان بازار سرمایه (دارا)","https://dara.csdiran.ir/login","💰 امور بانکی، مالی و مالیاتی"),
new LinkItem("بیمه ورزشی","https://athlete.ifsm.ir/login","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("تأمین اجتماعی","https://account.tamin.ir/auth/login","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("بیمه بیکاری","https://prkar.mcls.gov.ir","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("بیمه سلامت همگانی","https://hir.ihio.gov.ir/","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("کار و رفاه اجتماعی","https://www.mcls.gov.ir/","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("سامانه اظهار کارگاهی","https://elist.tamin.ir","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("خدمات قانون کار (سهیل)","https://soha.mcls.gov.ir","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("بیمه روستایی","https://www.roostaa.ir/","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("سامانه اشتغال (کارا)","https://kara.mcls.gov.ir","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("بیمه شخص ثالث","https://centralinsurance.ir","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("بیمه بازار","https://bimebazar.com","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("خدمات اشتغال مراکز کاریابی","https://karyab.mcls.gov.ir","🛠️ کار، بیمه و تأمین اجتماعی"),
new LinkItem("سهمیه سوخت","https://www.utcms.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("سایپا (ایران‌اکار)","https://saipa.iranecar.com/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("ایران‌خودرو","https://esale.ikco.ir/#!/Login?t=0","🚗 خودرو و حمل‌ونقل"),
new LinkItem("استعلام مالیات خودرو","https://cartransfer.tax.gov.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("کارت سوخت","https://fcs.niopdc.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("راهور ناجا (پلاک و گواهینامه)","https://rahvar.gov.ir","🚗 خودرو و حمل‌ونقل"),
new LinkItem("سخا (مدارک خودرو)","https://sakha.epolice.ir/portal/login","🚗 خودرو و حمل‌ونقل"),
new LinkItem("نوبت‌دهی وام خودرو (طرح خودرو)","https://auto.dolat.ir","🚗 خودرو و حمل‌ونقل"),
new LinkItem("سازمان حمل و نقل","https://www.rmto.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("اوتوران (تاکسی اینترنتی)","https://ohtoran.com","🚗 خودرو و حمل‌ونقل"),
new LinkItem("راهور ۱۲۰","https://www.rahvar120.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("گواهینامه رانندگی","https://golastik.rahvar.gov.ir","🚗 خودرو و حمل‌ونقل"),
new LinkItem("بیمه بدنه و ثالث ایتول","https://itoll.com/bimeh","🚗 خودرو و حمل‌ونقل"),
new LinkItem("سامانه یکپارچه خودرو","https://esale.ikco.ir/#!/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("ایتول","https://itoll.com/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("استعلام و پرداخت خلافی خودرو و موتور","https://khalafi.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("گواهی نامه موتور","https://iranianmotorco.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("لاستیک بارز","https://barez.org/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("لاستیک کویر","https://kavirtire.ir/esale","🚗 خودرو و حمل‌ونقل"),
new LinkItem("ایران خودرو","https://customer.ikco.ir/","🚗 خودرو و حمل‌ونقل"),
new LinkItem("یافتن کد پستی","https://gnaf.post.ir/portal","🏛️ خدمات دولتی و قضایی"),
new LinkItem("گواهی کد پستی-سایت پست","https://gnaf.post.ir/v2/main","🏛️ خدمات دولتی و قضایی"),
new LinkItem("ورود دولت من","https://sso.my.gov.ir/login","🏛️ خدمات دولتی و قضایی"),
new LinkItem("درخواست طلاق (ماسیر)","https://masir.23055.ir/login","🏛️ خدمات دولتی و قضایی"),
new LinkItem("خدمات قضایی","https://adliran.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("سامانه سخا","https://sakha.epolice.ir/portal/login","🏛️ خدمات دولتی و قضایی"),
new LinkItem("خودنویس","https://khodnevis.mrud.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("درگاه ملی دولت هوشمند","https://dolat.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("احراز هویت دیجیتال (اهوال)","https://ahval.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("سامانه ثنا","https://adliran.ir/index.php/sabtename","🏛️ خدمات دولتی و قضایی"),
new LinkItem("ابلاغیه","https://adliran.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("ثبت احوال (ثبتahoal و اسناد)","https://sabteahval.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("کارت ملی هوشمند","https://inquiry.nacr.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("استعلام علت مراجعه (وحدت رویه)","https://tele.judiciary.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("املاک و اسناد (دفترخانه)","https://sanaml.espacenet.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("سامانه نظارت و ارزشیابی","https://oecd.mcls.gov.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("سازمان نظام مهندسی","https://brce.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("ثبت‌ثانی (فوریتی سند)","https://sanam.iri.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("خدمات ثامن (گواهی فوت و وارث)","https://thamen.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("آثار و دارایی دولت (آستی)","https://asty.my.gov.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("سامانه نیکوکاری و محرومیت‌زدایی","https://un.treatment.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("پنل پیشخوان دولت","https://my.panelpishkhan.ir/login","🏛️ خدمات دولتی و قضایی"),
new LinkItem("مسکن ملی","https://saman.mrud.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("خودرو فرسوده","https://nnhk.ir/auth/sso/login","🏛️ خدمات دولتی و قضایی"),
new LinkItem("پیشخوان رسالت","https://pishkhan.rqbank.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("گواهی پستی تأیید کد پستی","https://gnaf.post.ir/portal","🏛️ خدمات دولتی و قضایی"),
new LinkItem("ثبت نام کتاب درسی","https://irtextbook.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("نوبت‌دهی سازمان ثبت اسناد","https://my.ssaa.ir","🏛️ خدمات دولتی و قضایی"),
new LinkItem("املاک اسکان","https://amlak.mrud.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("سامانه حمایت","https://hemayat.sfara.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("احراز نشانی پست","https://ehraz.post.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("نیروهای مسلح (ساتا)","https://esata.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("بنیاد شهید","https://my.isaar.ir/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("گزینش آجا","https://gozinesh.aja.ir/portal/home/","🏛️ خدمات دولتی و قضایی"),
new LinkItem("سامانه سیمین","https://simin.hadafmandi.ir/login","🏛️ خدمات دولتی و قضایی"),
new LinkItem("فنی حرفه ای سایت اصلی","https://portaltvto.com/","🎓 آموزش و دانشگاه"),
new LinkItem("کودکستان یاب","http://satta.medu.ir","🎓 آموزش و دانشگاه"),
new LinkItem("تأییدیه تحصیلی","https://emt.medu.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("آموزشیار (دانشگاه آزاد)","https://stdn.iau.ir/Student/Pages/acmstd/loginPage.jsp","🎓 آموزش و دانشگاه"),
new LinkItem("آزمون دانشگاه آزاد","https://azmoon.iau.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("تأییدیه دانشگاه آزاد","https://inquiry.tagfa.iau.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("وام رفاه دانشجویی","https://refah.swf.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("سازمان سنجش","https://sanjesh.org/","🎓 آموزش و دانشگاه"),
new LinkItem("مای مدیو (شاد مدرسه)","https://my.medu.ir/login.html?1","🎓 آموزش و دانشگاه"),
new LinkItem("نمونه سوالات کانون","https://www.kanoon.ir/Public/ExamQuestions","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه شاد","https://web.shad.ir","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه آفتاب (دانشگاهیان)","https://aftab.medu.ir","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه تربیت","https://tarbiat.medu.ir","🎓 آموزش و دانشگاه"),
new LinkItem("ثبت‌نام الکترونیک مدارس","https://reg.medu.ir","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه مهدکودک و آموزش (مدیو)","https://kids.medu.ir","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه کارشناسی ارشد و دکتری (سنجش)","https://phd.online.sanjesh.org","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه کاردانی به کارشناسی","https://kaasani.online.sanjesh.org","🎓 آموزش و دانشگاه"),
new LinkItem("پرتال امتحانات هنرستان (فنی‌حرفه‌ای)","https://irtce.ir","🎓 آموزش و دانشگاه"),
new LinkItem("بنیاد ملی نخبگان","https://bmn.ir","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه موسسه آموزش عالی غیرانتفاعی","https://gheiremontaz.org","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه آموزش تکمیلی (فنی‌کده)","https://elearning.ir","🎓 آموزش و دانشگاه"),
new LinkItem("سامانه گلستان پیام نور","https://reg.pnu.ac.ir/home/Default.htm","🎓 آموزش و دانشگاه"),
new LinkItem("دوگانه کردن خودرو","https://gcr.niopdc.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("پرداخت هزینه گواهینامه فنی و حرفه ای","https://pay.portaltvto.com/pay/licence2","🎓 آموزش و دانشگاه"),
new LinkItem("نمایش گواهینامه های فنی و حرفه ای","https://azmoon.portaltvto.com/estelam/estelam","🎓 آموزش و دانشگاه"),
new LinkItem("کارت ورود به جلسه آزمون فنی و حرفه ای","https://azmoon.portaltvto.com/","🎓 آموزش و دانشگاه"),
new LinkItem("ادواری فنی حرفه ای","https://azmoon.irantvto.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("هم‌آوای علمی کاربردی","https://edu.uast.ac.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("مای سنجش","http://my.sanjesh.org","🎓 آموزش و دانشگاه"),
new LinkItem("جهاد دانشگاهی","https://hrtc.ir/","🎓 آموزش و دانشگاه"),
new LinkItem("دانشجویان بهزیستی","http://student.behzisti.net/","🎓 آموزش و دانشگاه"),
new LinkItem("ایتا وب","https://web.eitaa.com/","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("روبیکا وب","https://web.rubika.ir/","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("شاد وب","https://web.shad.ir/","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("بله وب","https://web.bale.ai","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("ایتا (نسخه دسکتاپ)","https://desk.eitaa.com","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("روبیکا (نسخه وب پلاس)","https://web-plus.rubika.ir","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("بیسیم","https://web.bissim.ir","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("گپ","https://web.gap.im","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("سروش پلاس","https://web.splus.ir","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("نشان (اسنپ الاکس‌مسگر)","https://social.snapp.ir","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("اینستاگرام","https://www.instagram.com","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("تلگرام وب","https://web.telegram.org","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("واتساپ وب","https://web.whatsapp.com","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("یوتیوب","https://www.youtube.com","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("آپارات","https://www.aparat.com","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("لینکدین","https://www.linkedin.com","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("سپند سرویس مدارس","https://irtusepand.ir/","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("ارزیابی توان مالی رسالت","https://user.imerat.ir/#/auth/login","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("ارزیابی مرآت","https://omerat.ir/#!/login","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("ام رسالت","https://www.mresalat.ir/fa","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("ثبت نام کتاب درسی","https://irtextbook.ir","📱 پیام‌رسان‌ها و شبکه‌های اجتماعی"),
new LinkItem("نشان","https://neshan.org/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("بلد","https://balad.ir/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("تبدیل عکس ۳×۴","https://opt.imum.ir/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("دارالقرآن","https://telavat.ir/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("پنل مبین‌نت","https://my.mobinnet.ir/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("مخابرات (قبض و پرداخت)","https://adsl.tci.ir/panel/quickpay","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("سدف (گاز خانوار)","https://www.niopdc.ir/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("بلیط ۷۸۰ (پرواز)","https://780.ir/tourism/flights","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("رجا (قطار)","https://www.raja.ir/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("قبضینو","https://ghabzino.com/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("ایتول","https://itoll.com/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("IlovePDF","https://www.ilovepdf.com","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("اسنپ","https://snapp.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("تپسی","https://tapsi.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("دیجی‌کالا","https://www.digikala.com","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("دیجی‌پی (درگاه پرداخت)","https://www.digipay.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("الوقت (تقویم و اوقات شرعی)","https://alwaset.com","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("نوبت‌دهی پزشکی (بهسا)","https://bms.medu.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("سامانه پست (رهگیری مرسولات)","https://tracking.post.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("زنجیره تأمین (تقاضای کارت یارانه)","https://eghlighi.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("سامانه اوقات پرواز پروازی","https://flightio.com","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("آفتاب‌نیوز (اخبار روز)","https://www.aftabnews.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("گوگل","https://www.google.com","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("گوگل درایو","https://drive.google.com","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("فونت فارسی","https://fontiran.com","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("برق من","https://bargheman.com/home","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("ایران‌خودرو (خدمات پس از فروش)","https://www.ikco.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("ساعت و زمان جهانی","https://time.ir","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("سهیم (انحصار وراثت)","https://dadbanan.com/post/593/سامانه-سهیم-و-گواهی-انحصار-وراثت","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("شمیم","#","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("چت GPT","https://chatgpt.com/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("چت DeepSeek","https://chat.deepseek.com/","🛠️ ابزارها، اینترنت و سایر"),
new LinkItem("چت Grok","https://grok.com/","🛠️ ابزارها، اینترنت و سایر")
            };
        }
    }
}
